package ru.sbrf.ufs.kmcib.entity;
// Generated 12.08.2016 19:39:46 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContactInfo generated by hbm2java
 */
@Entity
@Table(name="CONTACT_INFO"
    ,schema="PUBLIC"
    ,catalog="RMKMDB"
)
public class ContactInfo  implements java.io.Serializable {


     private String contactid;
     private PutTask putTask;

    public ContactInfo() {
    }

    public ContactInfo(String contactid, PutTask putTask) {
       this.contactid = contactid;
       this.putTask = putTask;
    }
   
     @Id 
    
    @Column(name="CONTACTID", unique=true, nullable=false, length=15)
    public String getContactid() {
        return this.contactid;
    }
    
    public void setContactid(String contactid) {
        this.contactid = contactid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PUTTASKID", nullable=false)
    public PutTask getPutTask() {
        return this.putTask;
    }
    
    public void setPutTask(PutTask putTask) {
        this.putTask = putTask;
    }




}


