package ru.sbrf.ufs.kmcib.entity;
// Generated 12.08.2016 19:39:46 by Hibernate Tools 3.2.2.GA


import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EcmDocumentContent generated by hbm2java
 */
@Entity
@Table(name="ECM_DOCUMENT_CONTENT"
    ,schema="PUBLIC"
    ,catalog="RMKMDB"
)
public class EcmDocumentContent  implements java.io.Serializable {


     private long id;
     private String type;
     private Blob content;
     private Set<EcmDocument> ecmDocuments = new HashSet<EcmDocument>(0);

    public EcmDocumentContent() {
    }

	
    public EcmDocumentContent(long id) {
        this.id = id;
    }
    public EcmDocumentContent(long id, String type, Blob content, Set<EcmDocument> ecmDocuments) {
       this.id = id;
       this.type = type;
       this.content = content;
       this.ecmDocuments = ecmDocuments;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="TYPE")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="CONTENT")
    public Blob getContent() {
        return this.content;
    }
    
    public void setContent(Blob content) {
        this.content = content;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ecmDocumentContent")
    public Set<EcmDocument> getEcmDocuments() {
        return this.ecmDocuments;
    }
    
    public void setEcmDocuments(Set<EcmDocument> ecmDocuments) {
        this.ecmDocuments = ecmDocuments;
    }




}


