package ru.sbrf.ufs.kmcib.entity;
// Generated 12.08.2016 19:39:46 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EcmDocument generated by hbm2java
 */
@Entity
@Table(name="ECM_DOCUMENT"
    ,schema="PUBLIC"
    ,catalog="RMKMDB"
)
public class EcmDocument  implements java.io.Serializable {


     private long id;
     private EcmDocumentContent ecmDocumentContent;
     private EcmDocument ecmDocument;
     private String name;
     private Boolean isfolder;
     private String attrs;
     private String class_;
     private String annotation;
     private Set<EcmDocument> ecmDocuments = new HashSet<EcmDocument>(0);

    public EcmDocument() {
    }

	
    public EcmDocument(long id) {
        this.id = id;
    }
    public EcmDocument(long id, EcmDocumentContent ecmDocumentContent, EcmDocument ecmDocument, String name, Boolean isfolder, String attrs, String class_, String annotation, Set<EcmDocument> ecmDocuments) {
       this.id = id;
       this.ecmDocumentContent = ecmDocumentContent;
       this.ecmDocument = ecmDocument;
       this.name = name;
       this.isfolder = isfolder;
       this.attrs = attrs;
       this.class_ = class_;
       this.annotation = annotation;
       this.ecmDocuments = ecmDocuments;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTENTID")
    public EcmDocumentContent getEcmDocumentContent() {
        return this.ecmDocumentContent;
    }
    
    public void setEcmDocumentContent(EcmDocumentContent ecmDocumentContent) {
        this.ecmDocumentContent = ecmDocumentContent;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PARENTID")
    public EcmDocument getEcmDocument() {
        return this.ecmDocument;
    }
    
    public void setEcmDocument(EcmDocument ecmDocument) {
        this.ecmDocument = ecmDocument;
    }
    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="ISFOLDER")
    public Boolean getIsfolder() {
        return this.isfolder;
    }
    
    public void setIsfolder(Boolean isfolder) {
        this.isfolder = isfolder;
    }
    
    @Column(name="ATTRS", length=200)
    public String getAttrs() {
        return this.attrs;
    }
    
    public void setAttrs(String attrs) {
        this.attrs = attrs;
    }
    
    @Column(name="CLASS", length=200)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }
    
    @Column(name="ANNOTATION", length=200)
    public String getAnnotation() {
        return this.annotation;
    }
    
    public void setAnnotation(String annotation) {
        this.annotation = annotation;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ecmDocument")
    public Set<EcmDocument> getEcmDocuments() {
        return this.ecmDocuments;
    }
    
    public void setEcmDocuments(Set<EcmDocument> ecmDocuments) {
        this.ecmDocuments = ecmDocuments;
    }




}


