package ru.sbrf.ufs.kmcib.entity;
// Generated 12.08.2016 19:39:46 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductInfo generated by hbm2java
 */
@Entity
@Table(name="PRODUCT_INFO"
    ,schema="PUBLIC"
    ,catalog="RMKMDB"
)
public class ProductInfo  implements java.io.Serializable {


     private String productid;
     private PutTask putTask;
     private String mdmid;
     private String productname;

    public ProductInfo() {
    }

	
    public ProductInfo(String productid, PutTask putTask) {
        this.productid = productid;
        this.putTask = putTask;
    }
    public ProductInfo(String productid, PutTask putTask, String mdmid, String productname) {
       this.productid = productid;
       this.putTask = putTask;
       this.mdmid = mdmid;
       this.productname = productname;
    }
   
     @Id 
    
    @Column(name="PRODUCTID", unique=true, nullable=false, length=15)
    public String getProductid() {
        return this.productid;
    }
    
    public void setProductid(String productid) {
        this.productid = productid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PUTTASKID", nullable=false)
    public PutTask getPutTask() {
        return this.putTask;
    }
    
    public void setPutTask(PutTask putTask) {
        this.putTask = putTask;
    }
    
    @Column(name="MDMID", length=15)
    public String getMdmid() {
        return this.mdmid;
    }
    
    public void setMdmid(String mdmid) {
        this.mdmid = mdmid;
    }
    
    @Column(name="PRODUCTNAME", length=100)
    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }




}


