package ru.sbrf.ufs.kmcib.entity;
// Generated 12.08.2016 19:39:46 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PutTask generated by hbm2java
 */
@Entity
@Table(name="PUT_TASK"
    ,schema="PUBLIC"
    ,catalog="RMKMDB"
)
public class PutTask  implements java.io.Serializable {


     private BigDecimal id;
     private String spname;
     private String systemid;
     private String method;
     private String divisioncrmid;
     private String login;
     private String inboundclientrequestid;
     private String actionid;
     private Date done;
     private String description;
     private String actiontype;
     private String status;
     private String priority;
     private String crmid;
     private String mdmid;
     private Date planned;
     private Date started;
     private String meetinglocation;
     private Date plannedcompletion;
     private String sbrfresult;
     private String sbrfdecision;
     private String audiofilename;
     private String area;
     private String channel;
     private String source;
     private String smsphonenumber;
     private String applicationcrmid;
     private String referencecrmid;
     private Clob response;
     private Set<TeamInfo> teamInfos = new HashSet<TeamInfo>(0);
     private Set<ProductInfo> productInfos = new HashSet<ProductInfo>(0);
     private Set<ContactInfo> contactInfos = new HashSet<ContactInfo>(0);

    public PutTask() {
    }

	
    public PutTask(BigDecimal id) {
        this.id = id;
    }
    public PutTask(BigDecimal id, String spname, String systemid, String method, String divisioncrmid, String login, String inboundclientrequestid, String actionid, Date done, String description, String actiontype, String status, String priority, String crmid, String mdmid, Date planned, Date started, String meetinglocation, Date plannedcompletion, String sbrfresult, String sbrfdecision, String audiofilename, String area, String channel, String source, String smsphonenumber, String applicationcrmid, String referencecrmid, Clob response, Set<TeamInfo> teamInfos, Set<ProductInfo> productInfos, Set<ContactInfo> contactInfos) {
       this.id = id;
       this.spname = spname;
       this.systemid = systemid;
       this.method = method;
       this.divisioncrmid = divisioncrmid;
       this.login = login;
       this.inboundclientrequestid = inboundclientrequestid;
       this.actionid = actionid;
       this.done = done;
       this.description = description;
       this.actiontype = actiontype;
       this.status = status;
       this.priority = priority;
       this.crmid = crmid;
       this.mdmid = mdmid;
       this.planned = planned;
       this.started = started;
       this.meetinglocation = meetinglocation;
       this.plannedcompletion = plannedcompletion;
       this.sbrfresult = sbrfresult;
       this.sbrfdecision = sbrfdecision;
       this.audiofilename = audiofilename;
       this.area = area;
       this.channel = channel;
       this.source = source;
       this.smsphonenumber = smsphonenumber;
       this.applicationcrmid = applicationcrmid;
       this.referencecrmid = referencecrmid;
       this.response = response;
       this.teamInfos = teamInfos;
       this.productInfos = productInfos;
       this.contactInfos = contactInfos;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=65535, scale=32767)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    
    @Column(name="SPNAME", length=80)
    public String getSpname() {
        return this.spname;
    }
    
    public void setSpname(String spname) {
        this.spname = spname;
    }
    
    @Column(name="SYSTEMID", length=80)
    public String getSystemid() {
        return this.systemid;
    }
    
    public void setSystemid(String systemid) {
        this.systemid = systemid;
    }
    
    @Column(name="METHOD", length=64)
    public String getMethod() {
        return this.method;
    }
    
    public void setMethod(String method) {
        this.method = method;
    }
    
    @Column(name="DIVISIONCRMID", length=15)
    public String getDivisioncrmid() {
        return this.divisioncrmid;
    }
    
    public void setDivisioncrmid(String divisioncrmid) {
        this.divisioncrmid = divisioncrmid;
    }
    
    @Column(name="LOGIN", length=50)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    
    @Column(name="INBOUNDCLIENTREQUESTID", length=15)
    public String getInboundclientrequestid() {
        return this.inboundclientrequestid;
    }
    
    public void setInboundclientrequestid(String inboundclientrequestid) {
        this.inboundclientrequestid = inboundclientrequestid;
    }
    
    @Column(name="ACTIONID", length=15)
    public String getActionid() {
        return this.actionid;
    }
    
    public void setActionid(String actionid) {
        this.actionid = actionid;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DONE", length=23)
    public Date getDone() {
        return this.done;
    }
    
    public void setDone(Date done) {
        this.done = done;
    }
    
    @Column(name="DESCRIPTION", length=1000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="ACTIONTYPE", length=50)
    public String getActiontype() {
        return this.actiontype;
    }
    
    public void setActiontype(String actiontype) {
        this.actiontype = actiontype;
    }
    
    @Column(name="STATUS", length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="PRIORITY", length=50)
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }
    
    @Column(name="CRMID", length=15)
    public String getCrmid() {
        return this.crmid;
    }
    
    public void setCrmid(String crmid) {
        this.crmid = crmid;
    }
    
    @Column(name="MDMID", length=20)
    public String getMdmid() {
        return this.mdmid;
    }
    
    public void setMdmid(String mdmid) {
        this.mdmid = mdmid;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PLANNED", length=23)
    public Date getPlanned() {
        return this.planned;
    }
    
    public void setPlanned(Date planned) {
        this.planned = planned;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STARTED", length=23)
    public Date getStarted() {
        return this.started;
    }
    
    public void setStarted(Date started) {
        this.started = started;
    }
    
    @Column(name="MEETINGLOCATION", length=100)
    public String getMeetinglocation() {
        return this.meetinglocation;
    }
    
    public void setMeetinglocation(String meetinglocation) {
        this.meetinglocation = meetinglocation;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PLANNEDCOMPLETION", length=23)
    public Date getPlannedcompletion() {
        return this.plannedcompletion;
    }
    
    public void setPlannedcompletion(Date plannedcompletion) {
        this.plannedcompletion = plannedcompletion;
    }
    
    @Column(name="SBRFRESULT", length=50)
    public String getSbrfresult() {
        return this.sbrfresult;
    }
    
    public void setSbrfresult(String sbrfresult) {
        this.sbrfresult = sbrfresult;
    }
    
    @Column(name="SBRFDECISION", length=200)
    public String getSbrfdecision() {
        return this.sbrfdecision;
    }
    
    public void setSbrfdecision(String sbrfdecision) {
        this.sbrfdecision = sbrfdecision;
    }
    
    @Column(name="AUDIOFILENAME")
    public String getAudiofilename() {
        return this.audiofilename;
    }
    
    public void setAudiofilename(String audiofilename) {
        this.audiofilename = audiofilename;
    }
    
    @Column(name="AREA", length=50)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    
    @Column(name="CHANNEL", length=50)
    public String getChannel() {
        return this.channel;
    }
    
    public void setChannel(String channel) {
        this.channel = channel;
    }
    
    @Column(name="SOURCE", length=100)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    
    @Column(name="SMSPHONENUMBER", length=50)
    public String getSmsphonenumber() {
        return this.smsphonenumber;
    }
    
    public void setSmsphonenumber(String smsphonenumber) {
        this.smsphonenumber = smsphonenumber;
    }
    
    @Column(name="APPLICATIONCRMID", length=15)
    public String getApplicationcrmid() {
        return this.applicationcrmid;
    }
    
    public void setApplicationcrmid(String applicationcrmid) {
        this.applicationcrmid = applicationcrmid;
    }
    
    @Column(name="REFERENCECRMID", length=15)
    public String getReferencecrmid() {
        return this.referencecrmid;
    }
    
    public void setReferencecrmid(String referencecrmid) {
        this.referencecrmid = referencecrmid;
    }
    
    @Column(name="RESPONSE")
    public Clob getResponse() {
        return this.response;
    }
    
    public void setResponse(Clob response) {
        this.response = response;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="putTask")
    public Set<TeamInfo> getTeamInfos() {
        return this.teamInfos;
    }
    
    public void setTeamInfos(Set<TeamInfo> teamInfos) {
        this.teamInfos = teamInfos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="putTask")
    public Set<ProductInfo> getProductInfos() {
        return this.productInfos;
    }
    
    public void setProductInfos(Set<ProductInfo> productInfos) {
        this.productInfos = productInfos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="putTask")
    public Set<ContactInfo> getContactInfos() {
        return this.contactInfos;
    }
    
    public void setContactInfos(Set<ContactInfo> contactInfos) {
        this.contactInfos = contactInfos;
    }




}


