package ru.sbrf.ufs.kmcib.entity;
// Generated 12.08.2016 19:39:46 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TaskDetails generated by hbm2java
 */
@Entity
@Table(name="TASK_DETAILS"
    ,schema="PUBLIC"
    ,catalog="RMKMDB"
)
public class TaskDetails  implements java.io.Serializable {


     private BigDecimal id;
     private String spname;
     private String systemid;
     private String method;
     private String messageLogin;
     private String messageActionid;
     private Clob response;

    public TaskDetails() {
    }

	
    public TaskDetails(BigDecimal id) {
        this.id = id;
    }
    public TaskDetails(BigDecimal id, String spname, String systemid, String method, String messageLogin, String messageActionid, Clob response) {
       this.id = id;
       this.spname = spname;
       this.systemid = systemid;
       this.method = method;
       this.messageLogin = messageLogin;
       this.messageActionid = messageActionid;
       this.response = response;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=65535, scale=32767)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    
    @Column(name="SPNAME", length=80)
    public String getSpname() {
        return this.spname;
    }
    
    public void setSpname(String spname) {
        this.spname = spname;
    }
    
    @Column(name="SYSTEMID", length=80)
    public String getSystemid() {
        return this.systemid;
    }
    
    public void setSystemid(String systemid) {
        this.systemid = systemid;
    }
    
    @Column(name="METHOD", length=64)
    public String getMethod() {
        return this.method;
    }
    
    public void setMethod(String method) {
        this.method = method;
    }
    
    @Column(name="MESSAGE_LOGIN", length=50)
    public String getMessageLogin() {
        return this.messageLogin;
    }
    
    public void setMessageLogin(String messageLogin) {
        this.messageLogin = messageLogin;
    }
    
    @Column(name="MESSAGE_ACTIONID", length=15)
    public String getMessageActionid() {
        return this.messageActionid;
    }
    
    public void setMessageActionid(String messageActionid) {
        this.messageActionid = messageActionid;
    }
    
    @Column(name="RESPONSE")
    public Clob getResponse() {
        return this.response;
    }
    
    public void setResponse(Clob response) {
        this.response = response;
    }




}


