package ru.sbrf.ufs.kmcib.entity;
// Generated 12.08.2016 19:39:46 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TaskList generated by hbm2java
 */
@Entity
@Table(name="TASK_LIST"
    ,schema="PUBLIC"
    ,catalog="RMKMDB"
)
public class TaskList  implements java.io.Serializable {


     private BigDecimal id;
     private String spname;
     private String systemid;
     private String method;
     private String userlogin;
     private String orgtype;
     private String orgnum;
     private String applicationtype;
     private String applicationcrmid;
     private String contactcrmid;
     private BigDecimal beforedays;
     private BigDecimal afterdays;
     private BigDecimal resultrecordcount;
     private BigDecimal resultpagenum;
     private Clob response;

    public TaskList() {
    }

	
    public TaskList(BigDecimal id) {
        this.id = id;
    }
    public TaskList(BigDecimal id, String spname, String systemid, String method, String userlogin, String orgtype, String orgnum, String applicationtype, String applicationcrmid, String contactcrmid, BigDecimal beforedays, BigDecimal afterdays, BigDecimal resultrecordcount, BigDecimal resultpagenum, Clob response) {
       this.id = id;
       this.spname = spname;
       this.systemid = systemid;
       this.method = method;
       this.userlogin = userlogin;
       this.orgtype = orgtype;
       this.orgnum = orgnum;
       this.applicationtype = applicationtype;
       this.applicationcrmid = applicationcrmid;
       this.contactcrmid = contactcrmid;
       this.beforedays = beforedays;
       this.afterdays = afterdays;
       this.resultrecordcount = resultrecordcount;
       this.resultpagenum = resultpagenum;
       this.response = response;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=65535, scale=32767)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    
    @Column(name="SPNAME", length=80)
    public String getSpname() {
        return this.spname;
    }
    
    public void setSpname(String spname) {
        this.spname = spname;
    }
    
    @Column(name="SYSTEMID", length=80)
    public String getSystemid() {
        return this.systemid;
    }
    
    public void setSystemid(String systemid) {
        this.systemid = systemid;
    }
    
    @Column(name="METHOD", length=64)
    public String getMethod() {
        return this.method;
    }
    
    public void setMethod(String method) {
        this.method = method;
    }
    
    @Column(name="USERLOGIN", length=50)
    public String getUserlogin() {
        return this.userlogin;
    }
    
    public void setUserlogin(String userlogin) {
        this.userlogin = userlogin;
    }
    
    @Column(name="ORGTYPE", length=80)
    public String getOrgtype() {
        return this.orgtype;
    }
    
    public void setOrgtype(String orgtype) {
        this.orgtype = orgtype;
    }
    
    @Column(name="ORGNUM", length=80)
    public String getOrgnum() {
        return this.orgnum;
    }
    
    public void setOrgnum(String orgnum) {
        this.orgnum = orgnum;
    }
    
    @Column(name="APPLICATIONTYPE", length=80)
    public String getApplicationtype() {
        return this.applicationtype;
    }
    
    public void setApplicationtype(String applicationtype) {
        this.applicationtype = applicationtype;
    }
    
    @Column(name="APPLICATIONCRMID", length=80)
    public String getApplicationcrmid() {
        return this.applicationcrmid;
    }
    
    public void setApplicationcrmid(String applicationcrmid) {
        this.applicationcrmid = applicationcrmid;
    }
    
    @Column(name="CONTACTCRMID", length=80)
    public String getContactcrmid() {
        return this.contactcrmid;
    }
    
    public void setContactcrmid(String contactcrmid) {
        this.contactcrmid = contactcrmid;
    }
    
    @Column(name="BEFOREDAYS", precision=65535, scale=32767)
    public BigDecimal getBeforedays() {
        return this.beforedays;
    }
    
    public void setBeforedays(BigDecimal beforedays) {
        this.beforedays = beforedays;
    }
    
    @Column(name="AFTERDAYS", precision=65535, scale=32767)
    public BigDecimal getAfterdays() {
        return this.afterdays;
    }
    
    public void setAfterdays(BigDecimal afterdays) {
        this.afterdays = afterdays;
    }
    
    @Column(name="RESULTRECORDCOUNT", precision=65535, scale=32767)
    public BigDecimal getResultrecordcount() {
        return this.resultrecordcount;
    }
    
    public void setResultrecordcount(BigDecimal resultrecordcount) {
        this.resultrecordcount = resultrecordcount;
    }
    
    @Column(name="RESULTPAGENUM", precision=65535, scale=32767)
    public BigDecimal getResultpagenum() {
        return this.resultpagenum;
    }
    
    public void setResultpagenum(BigDecimal resultpagenum) {
        this.resultpagenum = resultpagenum;
    }
    
    @Column(name="RESPONSE")
    public Clob getResponse() {
        return this.response;
    }
    
    public void setResponse(Clob response) {
        this.response = response;
    }




}


