package ru.sbrf.ufs.kmcib.entity;
// Generated 12.08.2016 19:39:46 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TeamInfo generated by hbm2java
 */
@Entity
@Table(name="TEAM_INFO"
    ,schema="PUBLIC"
    ,catalog="RMKMDB"
)
public class TeamInfo  implements java.io.Serializable {


     private String teamlogin;
     private PutTask putTask;
     private String sbrfactionrole;
     private String primaryflag;

    public TeamInfo() {
    }

	
    public TeamInfo(String teamlogin, PutTask putTask) {
        this.teamlogin = teamlogin;
        this.putTask = putTask;
    }
    public TeamInfo(String teamlogin, PutTask putTask, String sbrfactionrole, String primaryflag) {
       this.teamlogin = teamlogin;
       this.putTask = putTask;
       this.sbrfactionrole = sbrfactionrole;
       this.primaryflag = primaryflag;
    }
   
     @Id 
    
    @Column(name="TEAMLOGIN", unique=true, nullable=false, length=50)
    public String getTeamlogin() {
        return this.teamlogin;
    }
    
    public void setTeamlogin(String teamlogin) {
        this.teamlogin = teamlogin;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PUTTASKID", nullable=false)
    public PutTask getPutTask() {
        return this.putTask;
    }
    
    public void setPutTask(PutTask putTask) {
        this.putTask = putTask;
    }
    
    @Column(name="SBRFACTIONROLE", length=50)
    public String getSbrfactionrole() {
        return this.sbrfactionrole;
    }
    
    public void setSbrfactionrole(String sbrfactionrole) {
        this.sbrfactionrole = sbrfactionrole;
    }
    
    @Column(name="PRIMARYFLAG", length=2)
    public String getPrimaryflag() {
        return this.primaryflag;
    }
    
    public void setPrimaryflag(String primaryflag) {
        this.primaryflag = primaryflag;
    }




}


